### ISSUE TITLE
Starting the application with the default config fails

### ISSUE THREAD

**Issue by beaugunderson** [inaturalist/inatVisionAPI#20]
Error:

```Traceback (most recent call last):
  File "/Users/beau/p/inatVisionAPI/app.py", line 25, in <module>
    api = InatVisionAPI(CONFIG)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beau/p/inatVisionAPI/./lib/inat_vision_api.py", line 17, in __init__
    self.setup_inferrer(config["models"][0])
  File "/Users/beau/p/inatVisionAPI/./lib/inat_vision_api.py", line 33, in setup_inferrer
    self.inferrer = InatInferrer(config)
                    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/beau/p/inatVisionAPI/./lib/inat_inferrer.py", line 28, in __init__
    self.setup_taxonomy()
  File "/Users/beau/p/inatVisionAPI/./lib/inat_inferrer.py", line 36, in setup_taxonomy
    self.taxonomy = ModelTaxonomyDataframe(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beau/p/inatVisionAPI/lib/model_taxonomy_dataframe.py", line 7, in __init__
    self.load_mapping(path, thresholds_path)
  File "/Users/beau/p/inatVisionAPI/lib/model_taxonomy_dataframe.py", line 11, in load_mapping
    self.df = pd.read_csv(
              ^^^^^^^^^^^^
  File "/Users/beau/.envs/inat-vision/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beau/.envs/inat-vision/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beau/.envs/inat-vision/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beau/.envs/inat-vision/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/Users/beau/.envs/inat-vision/lib/python3.11/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'models/.../taxonomy.csv'
```

Where can the models be retrieved from?

**Comment by alexshepard** [comment]
Hi Beau,

We don't share our models publicly. You could train your own models or perhaps find one from one of the model zoos and adapt it.

Best wishes,
Alex

**Comment by beaugunderson** [comment]
Ah. Can you put a note to that effect in the README?

**Comment by alexshepard** [comment]
done, thanks for the suggestion
